service: karsoClientLoginSignupService
provider:
  name: aws
  runtime: nodejs20.x
  stage: develop
  region: us-west-2
functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /{proxy+}
          method: any